# Generated by Django 5.2.4 on 2026-01-06 06:56

from django.db import migrations

COIN_DATA = {
      'BTCUSDT': { 'name': 'Bitcoin', 'symbol': 'BTC', 'icon': '₿' },
      'ETHUSDT': { 'name': 'Ethereum', 'symbol': 'ETH', 'icon': 'Ξ' },
      'BNBUSDT': { 'name': 'BNB', 'symbol': 'BNB', 'icon': 'BNB' },
      'SOLUSDT': { 'name': 'Solana', 'symbol': 'SOL', 'icon': 'SOL' },
      'DOGEUSDT': { 'name': 'Dogecoin', 'symbol': 'DOGE', 'icon': 'Ð' },
      'ADAUSDT': { 'name': 'Cardano', 'symbol': 'ADA', 'icon': 'ADA' },
      'XRPUSDT': { 'name': 'XRP', 'symbol': 'XRP', 'icon': 'XRP' },
      'DOTUSDT': { 'name': 'Polkadot', 'symbol': 'DOT', 'icon': 'DOT' },
      'LTCUSDT': { 'name': 'Litecoin', 'symbol': 'LTC', 'icon': 'LTC' },
      'LINKUSDT': { 'name': 'Chainlink', 'symbol': 'LINK', 'icon': 'LINK' },
      'XLMUSDT': { 'name': 'Stellar', 'symbol': 'XLM', 'icon': 'XLM' },
      'BCHUSDT': { 'name': 'Bitcoin Cash', 'symbol': 'BCH', 'icon': 'BCH' },
      'ALGOUSDT': { 'name': 'Algorand', 'symbol': 'ALGO', 'icon': 'ALGO' },
      'VETUSDT': { 'name': 'VeChain', 'symbol': 'VET', 'icon': 'VET' },
      'ICPUSDT': { 'name': 'Internet Computer', 'symbol': 'ICP', 'icon': 'ICP' },
      'MATICUSDT': { 'name': 'Polygon', 'symbol': 'MATIC', 'icon': 'MATIC' },
      'FILUSDT': { 'name': 'Filecoin', 'symbol': 'FIL', 'icon': 'FIL' },
      'TRXUSDT': { 'name': 'TRON', 'symbol': 'TRX', 'icon': 'TRX' },
      'ETCUSDT': { 'name': 'Ethereum Classic', 'symbol': 'ETC', 'icon': 'ETC' },
      'ATOMUSDT': { 'name': 'Cosmos', 'symbol': 'ATOM', 'icon': 'ATOM' },
      'AVAXUSDT': { 'name': 'Avalanche', 'symbol': 'AVAX', 'icon': 'AVAX' },
      'XMRUSDT': { 'name': 'Monero', 'symbol': 'XMR', 'icon': 'XMR' },
      'EOSUSDT': { 'name': 'EOS', 'symbol': 'EOS', 'icon': 'EOS' },
      'NEOUSDT': { 'name': 'NEO', 'symbol': 'NEO', 'icon': 'NEO' },
      'XTZUSDT': { 'name': 'Tezos', 'symbol': 'XTZ', 'icon': 'XTZ' },
      'AAVEUSDT': { 'name': 'Aave', 'symbol': 'AAVE', 'icon': 'AAVE' },
      'MKRUSDT': { 'name': 'Maker', 'symbol': 'MKR', 'icon': 'MKR' },
      'COMPUSDT': { 'name': 'Compound', 'symbol': 'COMP', 'icon': 'COMP' },
      'UNIUSDT': { 'name': 'Uniswap', 'symbol': 'UNI', 'icon': 'UNI' },
      'YFIUSDT': { 'name': 'yearn.finance', 'symbol': 'YFI', 'icon': 'YFI' },
      'SHIBUSDT': { 'name': 'Shiba Inu', 'symbol': 'SHIB', 'icon': 'SHIB' },
      'INJUSDT': { 'name': 'Injective', 'symbol': 'INJ', 'icon': 'INJ' },
      'RUNEUSDT': { 'name': 'THORChain', 'symbol': 'RUNE', 'icon': 'RUNE' },
      'GRTUSDT': { 'name': 'The Graph', 'symbol': 'GRT', 'icon': 'GRT' },
      'CRVUSDT': { 'name': 'Curve DAO', 'symbol': 'CRV', 'icon': 'CRV' },
      'SANDUSDT': { 'name': 'The Sandbox', 'symbol': 'SAND', 'icon': 'SAND' },
      'MANAUSDT': { 'name': 'Decentraland', 'symbol': 'MANA', 'icon': 'MANA' },
      'ENJUSDT': { 'name': 'Enjin Coin', 'symbol': 'ENJ', 'icon': 'ENJ' },
      'AXSUSDT': { 'name': 'Axie Infinity', 'symbol': 'AXS', 'icon': 'AXS' },
      'CHZUSDT': { 'name': 'Chiliz', 'symbol': 'CHZ', 'icon': 'CHZ' },
      'FLOWUSDT': { 'name': 'Flow', 'symbol': 'FLOW', 'icon': 'FLOW' },
      'FTMUSDT': { 'name': 'Fantom', 'symbol': 'FTM', 'icon': 'FTM' },
      'GALAUSDT': { 'name': 'Gala', 'symbol': 'GALA', 'icon': 'GALA' },
      'APEUSDT': { 'name': 'ApeCoin', 'symbol': 'APE', 'icon': 'APE' },
      'THETAUSDT': { 'name': 'Theta Network', 'symbol': 'THETA', 'icon': 'THETA' },
      'ZILUSDT': { 'name': 'Zilliqa', 'symbol': 'ZIL', 'icon': 'ZIL' },
      'HBARUSDT': { 'name': 'Hedera', 'symbol': 'HBAR', 'icon': 'HBAR' },
      'ARPAUSDT': { 'name': 'ARPA', 'symbol': 'ARPA', 'icon': 'ARPA' },
      'KAVAUSDT': { 'name': 'Kava', 'symbol': 'KAVA', 'icon': 'KAVA' },
      'ONEUSDT': { 'name': 'Harmony', 'symbol': 'ONE', 'icon': 'ONE' },
      'ROSEUSDT': { 'name': 'Oasis Network', 'symbol': 'ROSE', 'icon': 'ROSE' },
      'ANKRUSDT': { 'name': 'Ankr', 'symbol': 'ANKR', 'icon': 'ANKR' },
      'SXPUSDT': { 'name': 'SXP', 'symbol': 'SXP', 'icon': 'SXP' },
      'LRCUSDT': { 'name': 'Loopring', 'symbol': 'LRC', 'icon': 'LRC' },
      'ZECUSDT': { 'name': 'Zcash', 'symbol': 'ZEC', 'icon': 'ZEC' },
      'DASHUSDT': { 'name': 'Dash', 'symbol': 'DASH', 'icon': 'DASH' }
}

def populate_coins(apps, schema_editor):
    Coin = apps.get_model('prices', 'Coin')
    for symbol, data in COIN_DATA.items():
        Coin.objects.create(
            symbol=symbol,
            name=data['name'],
            icon=data['icon']
        )

def remove_coins(apps, schema_editor):
    Coin = apps.get_model('prices', 'Coin')
    Coin.objects.filter(symbol__in=COIN_DATA.keys()).delete()

class Migration(migrations.Migration):

    dependencies = [
        ("prices", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(populate_coins, remove_coins),
    ]
